#!/usr/bin/env python3
"""Aggregate recurring weaknesses across vault audits into a learning note.
Usage: python cross_learn.py [--vault <dir>]

Scans every Audit-*.md (and Template-*.md) note, extracts CWE tags, and builds
a frequency map: which CWEs recur across projects. Writes `Common-Mistakes.md`
with a ranked table + a suggested-guardrails section. The MOC (vault_index.py)
auto-links this note under "Cross-Project Learnings", so the KB self-improves.
Idempotent — rerun after each audit.
"""
import os, re, argparse, datetime
from collections import defaultdict

CWE_RE = re.compile(r"CWE-\d+")
SKIP = {"._chain", ".ok"}


def vault_path(explicit):
    if explicit:
        return explicit
    env = os.path.join(os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes")), ".env")
    v = None
    try:
        with open(env) as f:
            for line in f:
                if line.startswith("OBSIDIAN_VAULT_PATH="):
                    v = line.strip().split("=", 1)[1]
    except Exception:
        pass
    return v or os.path.expanduser("~/Documents/Obsidian Vault")


def iter_audit_notes(v):
    out = []
    for dp, dn, fn in os.walk(v):
        if set(dp.split(os.sep)) & SKIP:
            continue
        for name in fn:
            if name.endswith(".md") and (name.startswith("Audit-") or name.startswith("Template-")):
                out.append(os.path.join(dp, name))
    return sorted(out)


# one-line mitigation hint per CWE (extend as needed)
MITIGATION = {
    "CWE-78": "Avoid shell=True; pass arg lists to subprocess, quote/validate inputs.",
    "CWE-89": "Use parameterized queries / ORM; never concat SQL from user input.",
    "CWE-95": "Never eval/exec untrusted input; use ast.literal_eval or a parser.",
    "CWE-502": "Use yaml.safe_load; avoid pickle on untrusted data.",
    "CWE-327": "Drop md5/sha1; use sha256+ for integrity, argon2/bcrypt for passwords.",
    "CWE-22": "Canonicalize + confine paths to a base dir; reject '..' segments.",
    "CWE-295": "Keep TLS verification on; pin certs instead of disabling.",
    "CWE-330": "Use secrets/system RNG for tokens, never random.*.",
    "CWE-489": "Gate debug mode behind env; never ship debug=True.",
    "CWE-798": "Load secrets from env/secret store, never hardcode.",
    "CWE-1078": "Resolve TODO/FIXME before release.",
    "CWE-1395": "Upgrade vulnerable dependency; track advisories via pip-audit.",
    "CWE-1104": "Pin and audit dependencies; install pip-audit in CI.",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault")
    a = ap.parse_args()
    v = vault_path(a.vault)
    notes = iter_audit_notes(v)
    if not notes:
        print("no Audit-/Template- notes found.")
        return

    cwe_projects = defaultdict(set)
    cwe_count = defaultdict(int)
    for p in notes:
        proj = os.path.splitext(os.path.basename(p))[0]
        try:
            with open(p, encoding="utf-8") as f:
                txt = f.read()
        except Exception:
            continue
        for m in CWE_RE.findall(txt):
            cwe_projects[m].add(proj)
            cwe_count[m] += 1

    ranked = sorted(cwe_count, key=lambda c: (-len(cwe_projects[c]), -cwe_count[c]))
    today = datetime.date.today().isoformat()

    lines = ["---", "tags: learning", f"updated: {today}", "---", ""]
    lines.append("# Common Mistakes (cross-project)")
    lines.append("")
    all_projects = {p for s in cwe_projects.values() for p in s}
    lines.append(f"> auto-generated by `cross_learn.py` on {today} from {len(notes)} notes.")
    lines.append(f"> {len(cwe_projects)} distinct CWE across {len(all_projects)} projects.")
    lines.append("")
    lines.append("## Recurring CWE")
    lines.append("")
    lines.append("| CWE | Times | Projects | Severity hint |")
    lines.append("|-----|-------|----------|---------------|")
    for c in ranked:
        projs = ", ".join(sorted(cwe_projects[c]))
        lines.append(f"| {c} | {cwe_count[c]} | {projs} | {MITIGATION.get(c, 'review')} |")
    lines.append("")

    # guardrails: CWEs seen in >=2 projects are systemic
    systemic = [c for c in ranked if len(cwe_projects[c]) >= 2]
    lines.append("## Suggested guardrails")
    lines.append("")
    if systemic:
        lines.append("These CWEs recur across multiple projects — add to the project's")
        lines.append("pre-merge checklist / CI gate:")
        lines.append("")
        for c in systemic:
            lines.append(f"- **{c}** ({len(cwe_projects[c])} projects): {MITIGATION.get(c, 'review')}")
    else:
        lines.append("- _no CWE recurs across >=2 projects yet — keep auditing._")
    lines.append("")
    lines.append("## Per-CWE mitigation")
    lines.append("")
    for c in ranked:
        lines.append(f"- **{c}**: {MITIGATION.get(c, 'review')}")
    lines.append("")

    out = "\n".join(lines)
    dst = os.path.join(v, "Common-Mistakes.md")
    with open(dst, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {dst} — {len(cwe_projects)} CWE, {len(systemic)} systemic (>=2 projects)")


if __name__ == "__main__":
    main()
