#!/usr/bin/env python3
"""Generate minimal, *meaningful* test skeletons from source modules.
Stdlib only (ast). Usage: python gen_tests.py <project_path> [--framework pytest|unittest]

For every .py module under <project>/src, emits tests/<module>_test.py with one
test per public top-level function/class. Unlike a pure smoke stub, it reads the
function signature + return annotation (via ast) and emits:
  * typed dummy arguments (int->0, str->"", list->[], ...) so the call runs
  * an `isinstance(result, <ret_type>)` assertion when the return type is a
    simple name (int, str, list, ...), else `assert result is not None`
This means a broken implementation (wrong return type / bad computation) is
actually caught by the audit.py --run-tests gate (#2) instead of passing through.
Skips modules that already have a test file. Pair with audit.py.
"""
import os, sys, ast, argparse

SRC_REL = "src"
TEST_REL = "tests"

# annotation name -> dummy literal for a safe call argument
LITERAL = {
    "int": "0", "float": "0.0", "complex": "0j", "str": '""', "bool": "False",
    "bytes": 'b""', "list": "[]", "dict": "{}", "tuple": "()", "set": "set()",
    "None": "None", "NoneType": "None", "object": "object()",
}


def arg_literal(ann):
    """Return a safe dummy literal for an annotation ast node."""
    if ann is None:
        return "None"
    if isinstance(ann, ast.Name):
        return LITERAL.get(ann.id, "None")
    if isinstance(ann, ast.Subscript):
        # List[int], Dict[str,int], Optional[str], ... -> use the container base
        base = ann.value
        if isinstance(base, ast.Name):
            return LITERAL.get(base.id, "None")
    if isinstance(ann, (ast.Constant,)) and ann.value is None:
        return "None"
    return "None"


def ret_name(ann):
    """If the return annotation is a simple name, return it (for isinstance);
    else return None (caller falls back to `is not None`)."""
    if isinstance(ann, ast.Name):
        return ann.id
    return None


def public_symbols(path):
    """Return list of (kind, name, detail) for public top-level defs/classes.
    detail for funcs = (args_literals_str, ret_name_or_None, ret_src_or_None);
    detail for classes = list of public method names."""
    try:
        with open(path, encoding="utf-8") as f:
            tree = ast.parse(f.read())
    except Exception as e:
        print(f"  skip {path}: parse error {e}")
        return []
    syms = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name.startswith("_"):
                continue
            args = node.args.args + node.args.posonlyargs
            # drop self/cls
            params = [a for a in args if a.arg not in ("self", "cls")]
            lit = ", ".join(arg_literal(a.annotation) for a in params)
            rname = ret_name(node.returns)
            rsrc = ast.unparse(node.returns) if node.returns else None
            syms.append(("func", node.name, (lit, rname, rsrc)))
        elif isinstance(node, ast.ClassDef):
            if node.name.startswith("_"):
                continue
            methods = []
            ctor_lit = ""
            for sub in node.body:
                if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if sub.name == "__init__":
                        ps = [a for a in (sub.args.args + sub.args.posonlyargs)
                              if a.arg not in ("self", "cls")]
                        ctor_lit = ", ".join(arg_literal(a.annotation) for a in ps)
                    elif not sub.name.startswith("_"):
                        methods.append(sub.name)
            syms.append(("class", node.name, (ctor_lit, methods)))
    return syms


def render_pytest(module, syms):
    lines = [f'"""Tests for {module} (auto-generated by gen_tests.py)."""',
             "import os, sys",
             "sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))",
             f"from src import {module}",
             ""]
    for kind, name, detail in syms:
        lines.append("")
        if kind == "func":
            lit, rname, rsrc = detail
            lines.append(f"def test_{name}():")
            lines.append(f'    # TODO: replace dummy args ({lit}) with real inputs')
            lines.append(f"    result = {module}.{name}({lit})")
            if rname:
                lines.append(f"    assert isinstance(result, {rname})")
            else:
                lines.append(f"    assert result is not None  "
                             f"# expected return type: {rsrc or 'unknown'}")
        else:
            ctor_lit, methods = detail
            lines.append(f"def test_{name}_instantiate():")
            lines.append(f"    obj = {module}.{name}({ctor_lit})")
            lines.append(f"    assert isinstance(obj, {module}.{name})")
            for m in methods:
                lines.append(f"    assert hasattr(obj, {m!r})")
    lines.append("")
    return "\n".join(lines)


def render_unittest(module, syms):
    lines = [f'"""Tests for {module} (auto-generated by gen_tests.py)."""',
             "import unittest, os, sys",
             "sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))",
             f"from src import {module}",
             "", "",
             f"class Test{module.capitalize()}(unittest.TestCase):"]
    for kind, name, detail in syms:
        lines.append("")
        if kind == "func":
            lit, rname, rsrc = detail
            lines.append(f"    def test_{name}(self):")
            lines.append(f'        # TODO: replace dummy args ({lit}) with real inputs')
            lines.append(f"        result = {module}.{name}({lit})")
            if rname:
                lines.append(f"        self.assertIsInstance(result, {rname})")
            else:
                lines.append(f"        self.assertIsNotNone(result)  "
                             f"# expected return type: {rsrc or 'unknown'}")
        else:
            ctor_lit, methods = detail
            lines.append(f"    def test_{name}_instantiate(self):")
            lines.append(f"        obj = {module}.{name}({ctor_lit})")
            lines.append(f"        self.assertIsInstance(obj, {module}.{name})")
            for m in methods:
                lines.append(f"        self.assertTrue(hasattr(obj, {m!r}))")
    lines.append("")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    unittest.main()")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("project")
    ap.add_argument("--framework", choices=["pytest", "unittest"], default="unittest")
    a = ap.parse_args()
    root = os.path.abspath(a.project)
    src = os.path.join(root, SRC_REL)
    tests = os.path.join(root, TEST_REL)
    if not os.path.isdir(src):
        print(f"no {SRC_REL}/ dir in {root}")
        sys.exit(2)
    os.makedirs(tests, exist_ok=True)
    made = 0
    for name in sorted(os.listdir(src)):
        if not name.endswith(".py") or name in ("__init__.py", "__main__.py"):
            continue
        mod = name[:-3]
        tpath = os.path.join(tests, f"{mod}_test.py")
        if os.path.exists(tpath):
            print(f"  exists: tests/{mod}_test.py (skip)")
            continue
        syms = public_symbols(os.path.join(src, name))
        if not syms:
            print(f"  no public symbols: src/{name} (skip)")
            continue
        body = (render_pytest if a.framework == "pytest" else render_unittest)(mod, syms)
        with open(tpath, "w", encoding="utf-8") as f:
            f.write(body)
        made += 1
        print(f"  wrote tests/{mod}_test.py ({len(syms)} symbol(s))")
    if made:
        print(f"---\n{made} test file(s) generated with typed assertions. "
              f"Refine the dummy args, then run `audit.py <proj> --run-tests`.")
    else:
        print("---")
        print("0 test file(s) generated. Fill the TODOs, then run the suite.")


if __name__ == "__main__":
    main()
