#!/usr/bin/env python3
"""Generate minimal test skeletons from source modules. Stdlib only (ast).
Usage: python gen_tests.py <project_path> [--framework pytest|unittest]

For every .py module under <project>/src, emits tests/<module>_test.py with one
smoke test per public top-level function/class (names not starting with _).
Skips modules that already have a test file. Minimal by design: assertions only,
no magic. Pair with audit.py so "minimal" still means "tested".
"""
import os, sys, ast, argparse

SRC_REL = "src"
TEST_REL = "tests"


def public_symbols(path):
    """Return list of (kind, name) for public top-level defs/classes."""
    try:
        with open(path, encoding="utf-8") as f:
            tree = ast.parse(f.read())
    except Exception as e:
        print(f"  skip {path}: parse error {e}")
        return []
    syms = []
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if not node.name.startswith("_"):
                syms.append(("func", node.name))
        elif isinstance(node, ast.ClassDef):
            if not node.name.startswith("_"):
                syms.append(("class", node.name))
    return syms


def render_pytest(module, syms):
    lines = [f'"""Smoke tests for {module} (auto-generated by gen_tests.py)."""',
             "import os, sys",
             "sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))",
             f"from src import {module}",
             ""]
    for kind, name in syms:
        lines.append("")
        lines.append(f"def test_{name}_smoke():")
        if kind == "func":
            lines.append(f"    # TODO: call {module}.{name}(...) with minimal inputs")
            lines.append(f"    assert callable({module}.{name})")
        else:
            lines.append(f"    # TODO: instantiate {module}.{name} and assert invariants")
            lines.append(f"    assert isinstance({module}.{name}, type)")
    lines.append("")
    return "\n".join(lines)


def render_unittest(module, syms):
    lines = [f'"""Smoke tests for {module} (auto-generated by gen_tests.py)."""',
             "import unittest, os, sys",
             "sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))",
             f"from src import {module}",
             "",
             "",
             f"class Test{module.capitalize()}(unittest.TestCase):"]
    for kind, name in syms:
        lines.append("")
        lines.append(f"    def test_{name}_smoke(self):")
        if kind == "func":
            lines.append(f"        # TODO: call {module}.{name}(...) with minimal inputs")
            lines.append(f"        self.assertTrue(callable({module}.{name}))")
        else:
            lines.append(f"        # TODO: instantiate {module}.{name} and assert invariants")
            lines.append(f"        self.assertIsInstance({module}.{name}, type)")
    lines.append("")
    lines.append("")
    lines.append("if __name__ == \"__main__\":")
    lines.append("    unittest.main()")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("project")
    ap.add_argument("--framework", choices=["pytest", "unittest"], default="unittest")
    a = ap.parse_args()
    root = os.path.abspath(a.project)
    src = os.path.join(root, SRC_REL)
    tests = os.path.join(root, TEST_REL)
    if not os.path.isdir(src):
        print(f"no {SRC_REL}/ dir in {root}")
        sys.exit(2)
    os.makedirs(tests, exist_ok=True)
    made = 0
    for name in sorted(os.listdir(src)):
        if not name.endswith(".py") or name in ("__init__.py", "__main__.py"):
            continue
        mod = name[:-3]
        tpath = os.path.join(tests, f"{mod}_test.py")
        if os.path.exists(tpath):
            print(f"  exists: tests/{mod}_test.py (skip)")
            continue
        syms = public_symbols(os.path.join(src, name))
        if not syms:
            print(f"  no public symbols: src/{name} (skip)")
            continue
        body = (render_pytest if a.framework == "pytest" else render_unittest)(mod, syms)
        with open(tpath, "w", encoding="utf-8") as f:
            f.write(body)
        made += 1
        print(f"  wrote tests/{mod}_test.py ({len(syms)} symbol(s))")
    print(f"---\n{made} test file(s) generated. Fill the TODOs, then run the suite.")


if __name__ == "__main__":
    main()
