#!/usr/bin/env python3
"""Build an Obsidian MOC (Map of Content) for the vault.
Usage: python vault_index.py [--vault <dir>]

Scans all .md notes (excluding the index itself and chain internals),
groups them by prefix (Audit-*, Template-*, Common-*, else Other),
emits wikilinks, and auto-links related notes by shared CWE / tag keywords.
Writes <vault>/Index.md. Idempotent — regenerates each run.
"""
import os, sys, re, argparse, datetime
from collections import defaultdict

SKIP = {"._chain", ".ok"}
INDEX_NAME = "Index.md"
# which note prefixes to collect as MOC sections
SECTIONS = [
    ("Audits", "Audit-"),
    ("Architecture Templates", "Template-"),
    ("Cross-Project Learnings", "Common-"),
    ("Notes", ""),  # catch-all (excludes the ones above + Index)
]


def vault_path(explicit):
    if explicit:
        return explicit
    env = os.path.join(os.environ.get("HERMES_HOME", os.path.expanduser("~/.hermes")), ".env")
    v = None
    try:
        with open(env) as f:
            for line in f:
                if line.startswith("OBSIDIAN_VAULT_PATH="):
                    v = line.strip().split("=", 1)[1]
    except Exception:
        pass
    return v or os.path.expanduser("~/Documents/Obsidian Vault")


def iter_notes(v):
    out = []
    for dp, dn, fn in os.walk(v):
        parts = set(dp.split(os.sep))
        if parts & SKIP:
            continue
        for name in fn:
            if not name.endswith(".md") or name == INDEX_NAME:
                continue
            out.append(os.path.join(dp, name))
    return sorted(out)


def note_name(path, v):
    return os.path.splitext(os.path.basename(path))[0]


def extract_cwes(path):
    try:
        with open(path, encoding="utf-8") as f:
            txt = f.read()
    except Exception:
        return set()
    return set(re.findall(r"CWE-\d+", txt))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--vault")
    a = ap.parse_args()
    v = vault_path(a.vault)
    notes = iter_notes(v)
    if not notes:
        print("no notes found.")
        return

    # group
    groups = defaultdict(list)
    meta = {}
    for p in notes:
        nm = note_name(p, v)
        cwes = extract_cwes(p)
        meta[nm] = cwes
        placed = False
        for _, prefix in SECTIONS:
            if prefix and nm.startswith(prefix):
                groups[prefix].append(nm)
                placed = True
                break
        if not placed:
            groups[""].append(nm)

    today = datetime.date.today().isoformat()
    lines = ["---", "tags: moc", f"updated: {today}", "---", ""]
    lines.append("# Vault Index (MOC)")
    lines.append("")
    lines.append(f"> auto-generated by `vault_index.py` on {today}. {len(notes)} notes.")
    lines.append("")

    for title, prefix in SECTIONS:
        members = groups.get(prefix, [])
        if not members:
            continue
        lines.append(f"## {title}")
        lines.append("")
        for nm in sorted(members):
            cwes = sorted(meta[nm])
            tag = f"  `{' '.join(cwes)}`" if cwes else ""
            lines.append(f"- [[{nm}]]{tag}")
        lines.append("")

    # auto cross-links: notes sharing >=1 CWE
    lines.append("## Related by CWE")
    lines.append("")
    linked = False
    names = sorted(meta)
    for i, a_ in enumerate(names):
        for b_ in names[i + 1:]:
            shared = meta[a_] & meta[b_]
            if shared:
                linked = True
                lines.append(f"- [[{a_}]] ↔ [[{b_}]]  (`{' '.join(sorted(shared))}`)")
    if not linked:
        lines.append("- _no shared CWE yet_")
    lines.append("")

    out = "\n".join(lines)
    idx = os.path.join(v, INDEX_NAME)
    with open(idx, "w", encoding="utf-8") as f:
        f.write(out)
    print(f"wrote {idx} — {len(notes)} notes, "
          f"{sum(len(g) for g in groups.values())} indexed")


if __name__ == "__main__":
    main()
